services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-techtest-api
    depends_on:
      - mongo
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
